version: 0.2

env:
  secrets-manager:
     DOCKERHUB_PASS: "dockerhub:password"
     DOCKERHUB_USERNAME: "dockerhub:username"
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub 
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image          
      - docker build -t docker-hello-world .
      - docker tag docker-hello-world:latest afzalch/docker-hello-world
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Docker Hub
      - docker push afzalch/docker-hello-world:latest
