version: 0.2

env:
  secrets-manager:
     DOCKERHUB_PASS: "dockerhub:password"
     DOCKERHUB_USERNAME: "dockerhub:username"
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub 
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      # - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      # - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image          
      - docker build -t hello-world-python .
      - docker tag hello-world-python:latest afzalch/hello-world-python
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Docker Hub
      - docker push afzalch/hello-world-python:latest
